version: '3'
services:
  monalternancefacile:
    image: monalternancefacile:latest
    container_name: monalternancefacile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/app
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monalternancefacile